def get_nudge_block(assumption: dict) -> list:
def get_nudge_block(assumption):
    if not all(k in assumption for k in ('id', 'text')):
        raise ValueError("Assumption dictionary must contain 'id' and 'text' keys.")
    return [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f":alarm_clock: *Stale Assumption Alert*\n\nWe haven't tested this in a while:\n> *{assumption['text']}*\n\nDo we still believe this is true?"
            }
        },
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Still True (Keep)"},
                    "style": "primary",
                    "action_id": "keep_assumption",
                    "value": assumption['id']
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Invalid (Archive)"},
                    "style": "danger",
                    "action_id": "archive_assumption",
                    "value": assumption['id']
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Generate Experiment"},
                    "action_id": "gen_experiment_modal",
                    "value": assumption['text']
                }
            ]
        }
    ]

def get_ai_summary_block(ai_text: str) -> list:
    """Generates Slack blocks for an AI summary.

    Args:
        ai_text: The text of the AI analysis.

    Returns:
        A list of dictionaries representing Slack Block Kit UI elements.
    """
    return [
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": ":sparkles: *Evidently AI Analysis*"}
        },
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": ai_text}
        },
        {
            "type": "context",
            "elements": [{"type": "mrkdwn", "text": "Generated by Google Gemini via Evidently"}]
        }
    ]
